server.name: kibana
server.host: 0.0.0.0
elasticsearch.hosts: [ "http://elasticsearch:9200" ]

# Lock down global logging root to errors only (silencing info/startup clutter)
logging.root.level: error